image: tetraweb/php
before_script:
  - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )'
  - mkdir -p ~/.ssh
  - eval $(ssh-agent -s)
  - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'
development_deploy:
  only:
    - master
  script:
    - ssh-add <(echo "$TMIIDEV")
    - ssh attachments@35.240.234.157 "cd /home/attachments/TAMINI-RESERVATION && git pull origin master"
production_deploy:
  only:
    - tags
  script:
    - ssh-add <(echo "$TMIIPROD")
    - ssh attachments@35.240.235.157 "cd /home/attachments/TAMINI-RESERVATION && git pull origin master"
    